### ISSUE TITLE
spostare albo POP unict sul server di open data sicilia

### ISSUE THREAD

**Issue by cristianolongo** [aborruso/albo-pop#102]

**Comment by cristianolongo** [comment]
Allo stato attuale dopo lo spostamento il server restituisce 500 internal error. Non riesco a trovare i log di apache per capire quale sia il problema.

**Comment by cristianolongo** [comment]
Sul log si riscontra questo

[Thu Mar 10 23:43:06 2016] [warn] [client 93.37.185.99] mod_fcgid: stderr: PHP Fatal error:  Uncaught exception 'Exception' with message 'No such element with id boge' in /home/dev.opendatasicilia.it/public_html/albopop/unict/AlboUnictParser.php:162
[Thu Mar 10 23:43:06 2016] [warn] [client 93.37.185.99] mod_fcgid: stderr: Stack trace:
[Thu Mar 10 23:43:06 2016] [warn] [client 93.37.185.99] mod_fcgid: stderr: #0 /home/dev.opendatasicilia.it/public_html/albopop/unict/AlboUnictParser.php(146): AlboUnictParser->retrieveTable(Object(DOMDocument))
[Thu Mar 10 23:43:06 2016] [warn] [client 93.37.185.99] mod_fcgid: stderr: #1 /home/dev.opendatasicilia.it/public_html/albopop/unict/unict2RSS.php(26): AlboUnictParser->__construct()
[Thu Mar 10 23:43:06 2016] [warn] [client 93.37.185.99] mod_fcgid: stderr: #2 {main}
[Thu Mar 10 23:43:06 2016] [warn] [client 93.37.185.99] mod_fcgid: stderr:   thrown in /home/dev.opendatasicilia.it/public_html/albopop/unict/AlboUnictParser.php on line 162

Sembra che la chiamata $doc->getElementById("boge") restituisca null.

**Comment by cristianolongo** [comment]
applicato un workaround
